workflow changes for packer

diff --git a/.github/workflows/packer-validate.yml b/.github/workflows/packer-validate.yml
--- a/.github/workflows/packer-validate.yml
+++ b/.github/workflows/packer-validate.yml
@@ -18,11 +18,24 @@ jobs:
         with:
           packer_version: ${{ vars.PACKER_VERSION }}
 
+      - name: Run Packer init
+        run: packer init ./packer/custom-ami.pkr.hcl
+
       - name: Run Packer fmt
         id: packer-fmt
         run: |
-          packer fmt -check=true ./packer/custom-ami.pkr.hcl
+          if ! packer fmt -check=true ./packer/custom-ami.pkr.hcl; then
+            echo "Formatting check failed for custom-ami.pkr.hcl"
+            exit 1
+          fi
+          if ! packer fmt -check=true ./packer/variables.pkr.hcl; then
+            echo "Formatting check failed for variables.pkr.hcl"
+            exit 1
+          fi
 
       - name: Run Packer validate
         run: |
-          packer validate ./packer/custom-ami.pkr.hcl
+          if ! packer validate ./packer/custom-ami.pkr.hcl; then
+            echo "Validation failed for custom-ami.pkr.hcl"
+            exit 1
+          fi
